// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace SupraSonicWin.Native
{
    internal static unsafe partial class RustBindings
    {
        const string __DllName = "libsuprasonic_core";





        [DllImport(__DllName, EntryPoint = "suprasonic_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void suprasonic_init();

        [DllImport(__DllName, EntryPoint = "suprasonic_set_audio_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void suprasonic_set_audio_callback(delegate* unmanaged[Cdecl]<float*, uint, void> cb);

        [DllImport(__DllName, EntryPoint = "suprasonic_set_level_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void suprasonic_set_level_callback(delegate* unmanaged[Cdecl]<float, void> cb);

        [DllImport(__DllName, EntryPoint = "suprasonic_start_recording", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int suprasonic_start_recording();

        [DllImport(__DllName, EntryPoint = "suprasonic_stop_recording", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int suprasonic_stop_recording();


    }



}
